### ISSUE TITLE
Assignments are not tagged

### ISSUE THREAD

**Issue by patilav** [patricia5859/WebDevSpring2016#1]
Kindly tag your assignments moving on with next assignments.
Please send me an email with the revision link in mail for Assignment 2,3 at patil.av@husky.neu.edu so that I can grade it.

**Comment by patricia5859** [comment]
Hi Avanti,

Sorry for the inconvenience. But I am not able to tag my assignments.
I shall surely see a TA very soon and get it fixed.

Following are the links:

Assignment 2,3:
1. GitHub URL: https://github.com/patricia5859/WebDevSpring2016
2. OpenShift URL:
   webdev2016-bagzaipatricia.rhcloud.com/assignment/client/index.html

You can find all other links at :

http://webdev2016-bagzaipatricia.rhcloud.com/

Kindly, let me know if you need any other information.

Thanks for your help.

Best,

Patricia

**Comment by patilav** [comment]
can you please verify if this is the link for Assignment 3 : Server side Submission 

https://github.com/patricia5859/WebDevSpring2016/tree/bcd4efd834fa9f75ed1ed53c589d01de41f7e45d

**Comment by patricia5859** [comment]
https://github.com/patricia5859/WebDevSpring2016/tree/723ce0b1643630ad5e84767fa0e164813721c1d5

This is the link you are looking for.
Please let me know if you have any inconvenience, I shall see you whenever
you have time.

Apologies.

Thank you

Best,
Patricia

**Comment by patricia5859** [comment]
Hi Avanti,

A quick question. Were you able to have a look at the website now?

Thanks
